### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by ghost** [kimwoonggon/publicservant_AI#3]

**Comment by kimwoonggon** [comment]
안녕하세요
model.save_weights(파일명) 으로 해야 합니다.
그리고 모델을 불러올 때는 버트 모델을 정의한 이후,
그 모델에 model.load_weights(파일명) 으로 해야 합니다.
해보시고 안되면 또 질문 주시기 바랍니다.
 
 
-----Original Message-----
