### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sikaleo** [kimwoonggon/publicservant_AI#5]
제공해주신 keras bert (04-squad,05-korquad ipynb) 코드를 실행하다보면 

layer_num = 12
model = load_trained_model_from_checkpoint(
    config_path,
    checkpoint_path,
    training=False,
    trainable=True,
    seq_len=SEQ_LEN,)
model.summary()

부분에서 

seq_len 부분에서 IndexError: list index out of range 에러가 발생하는데요.
일단 올려놓으신 코드 그대로 실행하였습니다. 무엇이 잘못된걸까요?

**Comment by kimwoonggon** [comment]
https://github.com/kimwoonggon/publicservant_AI/blob/master/3_(HuggingFACE%2BTF2)BERT_LARGE_WITH_SQUAD_V1_1.ipynb
위 링크는 동일 내용, 텐서플로우 2 버전입니다.
최초 버전은 colab에서 버전 이슈 등으로 실행이 원활하지 않으니 위 버전을 실행해주셨으면 합니다..

8월 15일 내로 관련 자료들을 업데이트 할 예정입니다.
